In [15]:
import numpy as np

P = [1,1,1,2,2,2,3,3,3]
T = list(range(1,4))*3
h = [P[i] * T[i] for i in range(len(P))]

nT = 3
nP = 3
#Ptable = [[P[i*nT+j] for j in range(nP)] for i in range(nT)]
table = lambda x: np.array([[x[i*nT+j] for j in range(nP)] for i in range(nT)])
print(table(h))


P: [1, 1, 1, 2, 2, 2, 3, 3, 3]
T: [1, 2, 3, 1, 2, 3, 1, 2, 3]
h: [1, 2, 3, 2, 4, 6, 3, 6, 9]
[[1 2 3]
 [2 4 6]
 [3 6 9]]
